### ISSUE TITLE
Metadata Missing 

### ISSUE THREAD

**Issue by alyosama** [mbourgey/scRNA_GBM#1]
Hi @mbourgey , 

I am trying to use your data in my analysis, I read the paper and I didn't see the metadata such as cell types "OLC, GPC, Neuronal, Astrocytic, Mesenchymal,Classical" 

Would you mind if you provide this data to us?

**Comment by ccruizm** [comment]
Good day, I am also interested in getting the metadata from your study, any news on this? 

Thanks!

**Comment by mbourgey** [comment]
HI sorry Cristian. I was not able to add them yet. I'm in contact with the author who did the analysis and I will try to update the repo soon.


Sorry for the delay

Mathieu

-----
Mathieu Bourgey, PhD
Bioinformatics manager
Canadian Centre for Computational Genomics (C3G) - Montréal Node
McGill Genome Centre
http://computationalgenomics.ca/<https://exchange.mcgill.ca/owa/redir.aspx?SURL=3pOQIO2UvBGILiKVm3ijbA8Eyt-R6Rhq1iFYBATwschIFmeFdrnSCGgAdAB0AHAAOgAvAC8AYwBvAG0AcAB1AHQAYQB0AGkAbwBuAGEAbABnAGUAbgBvAG0AaQBjAHMALgBjAGEALwA.&URL=http%3a%2f%2fcomputationalgenomics.ca%2f><http://computationalgenomics.ca/>
________________________________

**Comment by ccruizm** [comment]
Thanks for your reply @mbourgey. Please let me know once the metadata is available.

**Comment by mbourgey** [comment]
HI Cristian, I still don't have any feedback from the 1st author (who has left for a postdoc last year).

I will check with other people from his lab if I can get the information

Mathieu

-----
Mathieu Bourgey, PhD
Bioinformatics manager
Canadian Centre for Computational Genomics (C3G) - Montréal Node
McGill Genome Centre
http://computationalgenomics.ca/<https://exchange.mcgill.ca/owa/redir.aspx?SURL=3pOQIO2UvBGILiKVm3ijbA8Eyt-R6Rhq1iFYBATwschIFmeFdrnSCGgAdAB0AHAAOgAvAC8AYwBvAG0AcAB1AHQAYQB0AGkAbwBuAGEAbABnAGUAbgBvAG0AaQBjAHMALgBjAGEALwA.&URL=http%3a%2f%2fcomputationalgenomics.ca%2f><http://computationalgenomics.ca/>
________________________________

**Comment by mbourgey** [comment]
HI Cristian,

the cell type annotation .mat file is now available from the repo I also added the corresponding enconding.

Thank you

Mathieu

-----
Mathieu Bourgey, PhD
Bioinformatics manager
Canadian Centre for Computational Genomics (C3G) - Montréal Node
McGill Genome Centre
http://computationalgenomics.ca/<https://exchange.mcgill.ca/owa/redir.aspx?SURL=3pOQIO2UvBGILiKVm3ijbA8Eyt-R6Rhq1iFYBATwschIFmeFdrnSCGgAdAB0AHAAOgAvAC8AYwBvAG0AcAB1AHQAYQB0AGkAbwBuAGEAbABnAGUAbgBvAG0AaQBjAHMALgBjAGEALwA.&URL=http%3a%2f%2fcomputationalgenomics.ca%2f><http://computationalgenomics.ca/>
________________________________

**Comment by kvittingseerup** [comment]
Would it be possible to provide the same for the normal cell types?
